# Generated by Django 3.2.8 on 2021-10-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('pincode', models.IntegerField(max_length=6)),
            ],
        ),
    ]
